package edu.neu.csye6200.View;

import edu.neu.csye6200.Model.DayCare;

import java.awt.*;

/**
 * @author duzhang
 */
public class StartScreen extends javax.swing.JPanel
{

    public StartScreen(DayCare daycare)
    {
        initComponents();
        this.daycare = daycare;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        btnStudents = new javax.swing.JButton();
        btnTeachers = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        jLabel1.setText("DayCare");

        btnStudents.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        btnStudents.setText("Manage Students");
        btnStudents.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnStudentsActionPerformed(evt);
            }
        });

        btnTeachers.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        btnTeachers.setText("Manage Teachers");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(227, 227, 227)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(btnTeachers, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                                                        .addComponent(btnStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(295, 295, 295)
                                                .addComponent(jLabel1)))
                                .addContainerGap(226, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel1)
                                .addGap(72, 72, 72)
                                .addComponent(btnStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnTeachers, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(256, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentsActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_btnStudentsActionPerformed
        StudentView studentView = new StudentView(daycare);
        this.getParent().add("StudentJPanel", studentView);
        CardLayout layout = (CardLayout) this.getParent().getLayout();
        layout.next(this.getParent());
    }//GEN-LAST:event_btnStudentsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStudents;
    private javax.swing.JButton btnTeachers;
    private javax.swing.JLabel jLabel1;
    private DayCare daycare;
    // End of variables declaration//GEN-END:variables
}
